name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: yarn install
        run: |
          yarn install
          mkdir -p .lighthousereports
      - name: run Lighthouse CI
        run: |
          ls -a
          yarn run lh
