name: CI
on:
  push:
    branches:
      - perf/**
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: yarn
        run: |
          yarn
      - name: run Lighthouse CI
        run: |
          yarn run lh
